#!/bin/bash

file="$1"  # Получаем имя файла в качестве аргумента

if [ -z "$file" ]; then
  	echo "Использование: $0 <имя_файла>"
  	file="/home/kwysst/.zshrc"
fi

if [ ! -f "$file" ]; then
  	echo "Файл '$file' не существует."
	exit 1
fi

# Находим номер строки, содержащей "unalias -a"
line_number=$(grep -n "unalias -a" "$file" | cut -d ":" -f 1)

if [ -z "$line_number" ]; then
  	echo "Строка 'unalias -a' не найдена в файле '$file'."
else
	sed -i "${line_number},\$d" "$file"
	echo "Содержимое файла '$file' удалено после строки 'unalias -a'."
fi


if [ -f "aliases.txt" ]; then
  	cat "aliases.txt" >> "$file"
  	echo "Содержимое файла 'aliases.txt' добавлено в конец файла '$file'."
  	exit 0
else
  	echo "Файл 'aliases.txt' не найден в текущей директории."
  	exit 1
fi

exit 0
