#!/bin/bash

RED='\e[31m'
GREEN='\e[32m'
RESET='\e[0m'

file="$1"  # Получаем имя файла в качестве аргумента

if [ -z "$file" ]; then
  	file="/home/kwysst/.zshrc"
fi

if [ ! -f "$file" ]; then
  	echo -e "${RED}Error: '$file' не существует.${RESET}"
	exit 1
fi

line_number=$(grep -n "unalias -a" "$file" | cut -d ":" -f 1)

if [ -z "$line_number" ]; then
  	echo -e "${GREEN}Предыдущих алиасов не существовало${RESET}"
else
	sed -i "${line_number},\$d" "$file"
	echo -e "${GREEN}Предыдущие алиасы были удалены${RESET}"
fi


if [ -f "aliases.txt" ]; then
  	cat "aliases.txt" >> "$file"
  	echo -e "${GREEN}Алиасы добавлены${RESET}"
  	exit 0
else
  	echo -e "${RED}Error: 'aliases.txt' не сущесвтует${RESET}"
  	exit 1
fi

exit 0
